#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx restart
