#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
echo "Hello World!" > sudo tee /var/www/html/index.html
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MJspitta permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default
sudo service nginx reload
