#!/usr/bin/env bash
# creates a file containing its pid and handles some signals

function handle_sigterm {
	echo "I hate the kill command"
}

function handle_sigint {
	echo "Y U no love me?!"
}

function handle_sigquit_sigterm {
	echo "I hate the kill command"
	rm /var/run/myscript.pid;
	exit 0
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit_sigterm SIGQUIT SIGTERM

echo $$ >> /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
