#!/usr/bin/env bash
# print statement indefinitely and another statement
# when receiving a SIGTERM signal

function handle_signal {
	echo "I am invincible!!!"
}

trap handle_signal SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
