#!/user/bin/env bash
# Configure ufw so that it blocks all incoming traffic
# except ports 22(SSH), 443(HTTPS SSL) and 80(HTTP)

# ufw installation
sudo apt install ufw

# default values
sudo ufw default deny incoming
sudo ufw default allow outgoing

# configuration
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# enable ufw and check status
sudo ufw enable
sudo ufw status verbose
